"""
Communication endpoint data schemas for API serialization and validation.

This module defines Pydantic models for communication endpoint-related data structures,
including request/response schemas for CRUD operations and data validation.
Communication endpoints define how devices connect and communicate over different mediums.
"""

from pydantic import BaseModel
from uuid import UUID
from ..models.enums import Medium, Profile
from typing import List, Optional


class CommunicationEndpoint(BaseModel):
    """
    Communication endpoint response schema.

    Represents a complete communication endpoint entity with all fields including
    the generated UUID identifier. Used for API responses when returning
    communication endpoint data to clients.

    Attributes:
        id: Unique identifier for the communication endpoint (UUID).
        device_id: UUID of the associated device.
        medium: Communication medium type (e.g., TCP, UDP, Serial).
        profile: Communication profile for DLMS/COSEM.
        ip: IP address for network-based communication.
        port: Port number for network-based communication.
        serial_port: Serial port name for serial communication.
        baud_rate: Baud rate for serial communication.
        is_primary: Whether this is the primary communication endpoint for the device.
    """

    id: UUID
    device_id: UUID
    medium: Medium
    profile: Profile
    ip: str
    port: int
    serial_port: str
    baud_rate: int
    is_primary: bool


class CommunicationEndpointList(BaseModel):
    """
    Communication endpoint list response schema.

    Container schema for returning multiple communication endpoints in a single
    API response. Used for paginated or bulk endpoint retrieval.

    Attributes:
        communication_endpoints: List of CommunicationEndpoint objects.
    """

    communication_endpoints: List[CommunicationEndpoint]


class CommunicationEndpointCreate(BaseModel):
    """
    Communication endpoint creation request schema.

    Schema for validating communication endpoint creation requests. Excludes
    the ID field as it's auto-generated by the database.

    Attributes:
        device_id: UUID of the associated device.
        medium: Communication medium type (e.g., TCP, UDP, Serial).
        profile: Communication profile for DLMS/COSEM.
        ip: IP address for network-based communication.
        port: Port number for network-based communication.
        serial_port: Serial port name for serial communication.
        baud_rate: Baud rate for serial communication.
        is_primary: Whether this is the primary communication endpoint for the device.
    """

    device_id: UUID
    medium: Medium
    profile: Profile
    ip: Optional[str] = None
    port: Optional[int] = None
    serial_port: Optional[str] = None
    baud_rate: Optional[int] = None
    is_primary: Optional[bool] = None


class CommunicationEndpointUpdate(BaseModel):
    """
    Communication endpoint update request schema.

    Schema for validating communication endpoint update requests. All fields
    are optional to allow partial updates. Only provided fields will be
    updated in the database.

    Attributes:
        medium: Optional new communication medium type.
        profile: Optional new communication profile.
        ip: Optional new IP address.
        port: Optional new port number.
        serial_port: Optional new serial port name.
        baud_rate: Optional new baud rate.
        is_primary: Optional new primary endpoint status.
    """

    medium: Optional[Medium] = None
    profile: Optional[Profile] = None
    ip: Optional[str] = None
    port: Optional[int] = None
    serial_port: Optional[str] = None
    baud_rate: Optional[int] = None
    is_primary: Optional[bool] = None
