"""
Device data schemas for API serialization and validation.

This module defines Pydantic models for device-related data structures,
including request/response schemas for CRUD operations and data validation.
"""

from pydantic import BaseModel, Field
from typing import Optional, List
from uuid import UUID

from .communication_endpoints import CommunicationEndpoint
from .device_addressing import DeviceAddressing


class Device(BaseModel):
    """
    Device response schema.

    Represents a complete device entity with all fields including
    the generated UUID identifier. Used for API responses when
    returning device data to clients.

    Attributes:
        id: Unique identifier for the device (UUID).
        name: Human-readable name of the device.
        description: Optional description of the device.
        serial_number: Unique serial number of the device.
        brand: Optional brand/manufacturer of the device.
        model: Optional model number of the device.
    """

    id: UUID
    name: str
    description: str = None
    serial_number: str
    brand: str = None
    model: str = None
    communication_endpoints: List[CommunicationEndpoint] = Field(default_factory=list)
    device_addressings: List[DeviceAddressing] = Field(default_factory=list)


class DeviceList(BaseModel):
    """
    Device list response schema.

    Container schema for returning multiple devices in a single
    API response. Used for paginated or bulk device retrieval.

    Attributes:
        devices: List of Device objects.
    """

    devices: List[Device]


class DeviceCreate(BaseModel):
    """
    Device creation request schema.

    Schema for validating device creation requests. Excludes
    the ID field as it's auto-generated by the database.

    Attributes:
        name: Human-readable name of the device.
        description: Optional description of the device.
        serial_number: Unique serial number of the device.
        brand: Optional brand/manufacturer of the device.
        model: Optional model number of the device.
    """

    name: str
    description: Optional[str] = None
    serial_number: Optional[str] = None
    brand: Optional[str] = None
    model: Optional[str] = None


class DeviceUpdate(BaseModel):
    """
    Device update request schema.

    Schema for validating device update requests. All fields
    are optional to allow partial updates. Only provided fields
    will be updated in the database.

    Attributes:
        name: Optional new name for the device.
        description: Optional new description for the device.
        serial_number: Optional new serial number for the device.
        brand: Optional new brand for the device.
        model: Optional new model for the device.
    """

    name: Optional[str] = None
    description: Optional[str] = None
    serial_number: Optional[str] = None
    brand: Optional[str] = None
    model: Optional[str] = None
