"""
Device addressing data schemas for API serialization and validation.

This module defines Pydantic models for device addressing-related data structures,
including request/response schemas for CRUD operations and data validation.
Device addressing defines the client and server addresses used for DLMS/COSEM
communication, along with addressing mode configuration.
"""

from typing import Optional, List
from pydantic import BaseModel
from uuid import UUID


class DeviceAddressing(BaseModel):
    """
    Device addressing response schema.

    Represents a complete device addressing entity with all fields including
    the generated UUID identifier. Used for API responses when returning
    device addressing data to clients.

    Attributes:
        id: Unique identifier for the device addressing configuration (UUID).
        endpoint_id: UUID of the associated communication endpoint.
        client_address: Client address for DLMS/COSEM communication.
        server_address: Server address for DLMS/COSEM communication.
        use_logical_name: Whether to use logical name addressing mode.
    """

    id: UUID
    device_id: UUID
    client_address: int
    server_address: int
    use_logical_name: bool


class DeviceAddressingList(BaseModel):
    """
    Device addressing list response schema.

    Container schema for returning multiple device addressing configurations
    in a single API response. Used for paginated or bulk addressing retrieval.

    Attributes:
        device_addressings: List of DeviceAddressing objects.
    """

    device_addressings: List[DeviceAddressing]


class DeviceAddressingCreate(BaseModel):
    """
    Device addressing creation request schema.

    Schema for validating device addressing creation requests. Excludes
    the ID field as it's auto-generated by the database.

    Attributes:
        device_id: UUID of the device to create addressing for.
        client_address: Client address for DLMS/COSEM communication.
        server_address: Server address for DLMS/COSEM communication.
        use_logical_name: Whether to use logical name addressing mode.
    """

    device_id: UUID
    client_address: int
    server_address: int
    use_logical_name: bool


class DeviceAddressingUpdate(BaseModel):
    """
    Device addressing update request schema.

    Schema for validating device addressing update requests. All fields
    are optional to allow partial updates. Only provided fields will be
    updated in the database.

    Attributes:
        client_address: Optional new client address for DLMS/COSEM communication.
        server_address: Optional new server address for DLMS/COSEM communication.
        use_logical_name: Optional new logical name addressing mode setting.
    """

    client_address: Optional[int] = None
    server_address: Optional[int] = None
    use_logical_name: Optional[bool] = None
