"""
Measurement data schemas for API serialization and validation.

This module defines Pydantic models for measurement-related data structures,
including request/response schemas for CRUD operations and data validation.
Measurements represent energy readings and other metering data captured
from DLMS/COSEM devices.
"""

from datetime import datetime
from pydantic import BaseModel
from uuid import UUID
from typing import Optional, List
from dlms_meter_communication.models.enums import Quantity, Direction, Phase


class Measurement(BaseModel):
    """
    Measurement response schema.

    Represents a complete measurement entity with all fields including
    the generated UUID identifier. Used for API responses when returning
    measurement data to clients.

    Attributes:
        id: Unique identifier for the measurement (UUID).
        device_id: UUID of the associated device.
        endpoint_id: UUID of the associated communication endpoint.
        obis: OBIS code identifying the measurement object.
        quantity: Type of quantity being measured (e.g., active energy, voltage).
        direction: Direction of the measurement (import, export, etc.).
        phase: Phase of the measurement (single, three-phase, etc.).
        value: Numerical value of the measurement.
        unit: Unit of measurement (e.g., kWh, V, A).
        ts_meter: Optional timestamp from the meter when the measurement was taken.
        ts_captured: Timestamp when the measurement was captured by the system.
    """

    id: UUID
    device_id: UUID
    endpoint_id: UUID
    obis: str
    quantity: Quantity
    direction: Direction
    phase: Phase
    value: float
    unit: str
    ts_meter: Optional[datetime] = None
    ts_captured: datetime


class MeasurementList(BaseModel):
    """
    Measurement list response schema.

    Container schema for returning multiple measurements in a single
    API response. Used for paginated or bulk measurement retrieval.

    Attributes:
        measurements: List of Measurement objects.
    """

    measurements: List[Measurement]


class MeasurementCreate(BaseModel):
    """
    Measurement creation request schema.

    Schema for validating measurement creation requests. Excludes
    the ID field as it's auto-generated by the database. The ts_captured
    field is typically set automatically by the system.

    Attributes:
        obis: OBIS code identifying the measurement object.
        quantity: Type of quantity being measured (e.g., active energy, voltage).
        direction: Direction of the measurement (import, export, etc.).
        phase: Phase of the measurement (single, three-phase, etc.).
        value: Numerical value of the measurement.
        unit: Unit of measurement (e.g., kWh, V, A).
        ts_meter: Optional timestamp from the meter when the measurement was taken.
    """

    obis: str
    quantity: Quantity
    direction: Direction
    phase: Phase
    value: float
    unit: str
    ts_meter: Optional[datetime] = None


class MeasurementUpdate(BaseModel):
    """
    Measurement update request schema.

    Schema for validating measurement update requests. All fields
    are optional to allow partial updates. Only provided fields will be
    updated in the database.

    Attributes:
        obis: Optional new OBIS code for the measurement.
        quantity: Optional new quantity type.
        direction: Optional new direction.
        phase: Optional new phase.
        value: Optional new measurement value.
        unit: Optional new unit of measurement.
        ts_meter: Optional new meter timestamp.
    """

    obis: Optional[str] = None
    quantity: Optional[Quantity] = None
    direction: Optional[Direction] = None
    phase: Optional[Phase] = None
    value: Optional[float] = None
    unit: Optional[str] = None
    ts_meter: Optional[datetime] = None
