"""
Negotiated parameters data schemas for API serialization and validation.

This module defines Pydantic models for negotiated parameters-related data structures,
including request/response schemas for CRUD operations and data validation.
Negotiated parameters store the communication parameters established during
DLMS/COSEM association negotiation between client and server.
"""

from pydantic import BaseModel
from uuid import UUID
from typing import Optional, List


class NegotiatedParams(BaseModel):
    """
    Negotiated parameters response schema.

    Represents a complete negotiated parameters entity with all fields including
    the generated UUID identifier. Used for API responses when returning
    negotiated parameters data to clients.

    Attributes:
        id: Unique identifier for the negotiated parameters (UUID).
        device_id: UUID of the associated device.
        endpoint_id: UUID of the associated communication endpoint.
        max_info_rx: Maximum information field length for receive operations.
        max_info_tx: Maximum information field length for transmit operations.
        win: Window size for HDLC communication.
        max_pdu: Maximum PDU (Protocol Data Unit) size.
    """

    id: UUID
    device_id: UUID
    endpoint_id: UUID
    max_info_rx: Optional[int] = None
    max_info_tx: Optional[int] = None
    win: Optional[int] = None
    max_pdu: Optional[int] = None


class NegotiatedParamsList(BaseModel):
    """
    Negotiated parameters list response schema.

    Container schema for returning multiple negotiated parameters in a single
    API response. Used for paginated or bulk parameters retrieval.

    Attributes:
        negotiated_params: List of NegotiatedParams objects.
    """

    negotiated_params: List[NegotiatedParams]


class NegotiatedParamsCreate(BaseModel):
    """
    Negotiated parameters creation request schema.

    Schema for validating negotiated parameters creation requests. Excludes
    the ID field as it's auto-generated by the database. All parameters
    are optional as they may not be available immediately after association.

    Attributes:
        max_info_rx: Optional maximum information field length for receive operations.
        max_info_tx: Optional maximum information field length for transmit operations.
        win: Optional window size for HDLC communication.
        max_pdu: Optional maximum PDU (Protocol Data Unit) size.
    """

    max_info_rx: Optional[int] = None
    max_info_tx: Optional[int] = None
    win: Optional[int] = None
    max_pdu: Optional[int] = None


class NegotiatedParamsUpdate(BaseModel):
    """
    Negotiated parameters update request schema.

    Schema for validating negotiated parameters update requests. All fields
    are optional to allow partial updates. Only provided fields will be
    updated in the database.

    Attributes:
        max_info_rx: Optional new maximum information field length for receive operations.
        max_info_tx: Optional new maximum information field length for transmit operations.
        win: Optional new window size for HDLC communication.
        max_pdu: Optional new maximum PDU (Protocol Data Unit) size.
    """

    max_info_rx: Optional[int] = None
    max_info_tx: Optional[int] = None
    win: Optional[int] = None
    max_pdu: Optional[int] = None
